version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=your_password_here  # เปลี่ยนเป็น password ที่ต้องการ
    command: redis-server --requirepass your_password_here --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "your_password_here", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis Commander - Web UI สำหรับจัดการ Redis (Optional)

volumes:
  redis_data: